Proquse
proquse/model pull request #119
Opened 2023-09-14 13:12 UTC by linusarnejohansson

rebranding everything to proquse except:

- logo 
  - we dont have a proquse logo yet
- all .json files
  - some of these affect whats being shown in npm so might as well skip the them and them all at once when ready

2023-09-14 13:27 UTC, TheLillyleaf requested changes

2023-09-14 13:27 UTC, TheLillyleaf commented on Key/Creatable.ts
>  	userwidgets.User.Key.Creatable.Claims,
github actions thing

2023-09-20 09:48 UTC, linusarnejohansson commented
no issuefab remain in the codebase

2023-09-20 10:38 UTC, EliasEriksson approved these changes
yolo

2023-09-20 10:55 UTC, TheLillyleaf approved these changes

2023-09-20 11:36 UTC, merged